steps:
# Сборка Docker образа
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcp-calendar:v1', '.']

# Отправка образа в Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mcp-calendar:v1']

# Дополнительно: развертывание в GKE (раскомментируйте и настройте при необходимости)
# - name: 'gcr.io/cloud-builders/kubectl'
#   args:
#   - 'apply'
#   - '-f'
#   - 'k8s/deployment.yaml'
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=YOUR_ZONE'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=YOUR_CLUSTER_NAME'

# Результат сборки - образ
images:
- 'gcr.io/$PROJECT_ID/mcp-calendar:v1'
